"""autojan17

Revision ID: 170e4f452291
Revises: 7946069f43c6
Create Date: 2024-01-17 13:55:10.946425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170e4f452291'
down_revision: Union[str, None] = '7946069f43c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_img_id'), 'catalog_img', ['id'], unique=False)
    op.drop_column('catalog', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_catalog_img_id'), table_name='catalog_img')
    op.drop_table('catalog_img')
    # ### end Alembic commands ###
