"""valid id and cert2

Revision ID: 31503bb78ff9
Revises: f5d2910e9bd3
Create Date: 2024-01-30 15:32:32.702195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31503bb78ff9'
down_revision: Union[str, None] = 'f5d2910e9bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('tiktok', sa.String(), nullable=True))
    op.add_column('business', sa.Column('has_valid_cert', sa.Integer(), nullable=True))
    op.add_column('business', sa.Column('has_valid_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'has_valid_id')
    op.drop_column('business', 'has_valid_cert')
    op.drop_column('business', 'tiktok')
    # ### end Alembic commands ###
