"""user lga

Revision ID: 5868082d6fcf
Revises: dc36ad5b1db6
Create Date: 2024-04-04 12:21:13.763647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5868082d6fcf'
down_revision: Union[str, None] = 'dc36ad5b1db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lga', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lga')
    op.drop_column('users', 'state')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
