"""referral

Revision ID: 5b9f3cfae583
Revises: 844da177cab0
Create Date: 2024-06-27 12:13:03.828940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9f3cfae583'
down_revision: Union[str, None] = '844da177cab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('referrer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referrer')
    op.drop_column('users', 'referral_code')
    # ### end Alembic commands ###
