"""sub price

Revision ID: 6a87dbfd2f5d
Revises: 170e4f452291
Create Date: 2024-01-20 07:56:53.771312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a87dbfd2f5d'
down_revision: Union[str, None] = '170e4f452291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_history', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('sub_history', sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('subscriptions', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'date_created')
    op.drop_column('subscriptions', 'price')
    op.drop_column('sub_history', 'date_created')
    op.drop_column('sub_history', 'price')
    # ### end Alembic commands ###
