"""sub price

Revision ID: 836968a3320a
Revises: 436ebdf314c9
Create Date: 2024-01-20 11:47:08.122967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836968a3320a'
down_revision: Union[str, None] = '436ebdf314c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_price_id'), 'sub_price', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_price_id'), table_name='sub_price')
    op.drop_table('sub_price')
    # ### end Alembic commands ###
