"""biz lga

Revision ID: 8a40bb1842ac
Revises: 5868082d6fcf
Create Date: 2024-04-04 12:36:00.976785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a40bb1842ac'
down_revision: Union[str, None] = '5868082d6fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('town', sa.String(), nullable=True))
    op.add_column('business', sa.Column('lga', sa.String(), nullable=True))
    op.drop_column('business', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('business', 'lga')
    op.drop_column('business', 'town')
    # ### end Alembic commands ###
