"""img default

Revision ID: 9526c05e8f8c
Revises: 207d3f0a6585
Create Date: 2024-01-23 14:19:16.741717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9526c05e8f8c'
down_revision: Union[str, None] = '207d3f0a6585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_img', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'catalog_img', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog_img', type_='foreignkey')
    op.drop_column('catalog_img', 'business_id')
    # ### end Alembic commands ###
