"""catimg2

Revision ID: b1ddfa73ef65
Revises: 25d997a7d526
Create Date: 2024-01-31 15:50:43.315460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ddfa73ef65'
down_revision: Union[str, None] = '25d997a7d526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog', 'image')
    # ### end Alembic commands ###
