"""sub price

Revision ID: dc36ad5b1db6
Revises: b51ad4bd6d83
Create Date: 2024-03-01 23:51:06.305982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc36ad5b1db6'
down_revision: Union[str, None] = 'b51ad4bd6d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_price', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('sub_price', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_price', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sub_price', 'name')
    # ### end Alembic commands ###
