"""hist date2

Revision ID: f84be3f9dc5e
Revises: 566566566f66
Create Date: 2024-01-20 23:26:45.241786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f84be3f9dc5e'
down_revision: Union[str, None] = '566566566f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_history', sa.Column('date_updated', sa.Date(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('sub_history', 'date_created')
    op.alter_column('sub_price', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_price', 'date_updated',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('sub_history', sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('sub_history', 'date_updated')
    # ### end Alembic commands ###
