"""hist date4

Revision ID: fcb485b8391c
Revises: f84be3f9dc5e
Create Date: 2024-01-20 23:56:35.122699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb485b8391c'
down_revision: Union[str, None] = 'f84be3f9dc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_history', 'date_updated',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sub_price', 'date_updated',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_price', 'date_updated',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sub_history', 'date_updated',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
