"""add geo

Revision ID: fd7830ba0d52
Revises: 8a40bb1842ac
Create Date: 2024-04-04 12:54:11.895058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7830ba0d52'
down_revision: Union[str, None] = '8a40bb1842ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('geo', sa.String(), nullable=True))
    op.alter_column('business', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('users', sa.Column('town', sa.String(), nullable=True))
    op.add_column('users', sa.Column('geo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'geo')
    op.drop_column('users', 'town')
    op.alter_column('business', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('business', 'geo')
    # ### end Alembic commands ###
